
class Constants:

    HORCRUX_NAME = "Horcrux hunter" 
    FONT = "Calibri"
    MODEL_FEATURE_COUNT = 5 
    NAVIGATION_BAR_HEIGHT = 30
    FPS = 10
    PIXEL_SIZE = 25
    SCREEN_WIDTH = 400
    SCREEN_HEIGHT = 350
    FRAMES_TO_REMEMBER = 4
    SCREEN_DEPTH = 32
    ENV_HEIGHT = int(SCREEN_HEIGHT/PIXEL_SIZE)
    ENV_WIDTH = int(SCREEN_WIDTH/PIXEL_SIZE)
